version: '2.2'

services:
  backend:
    restart: always
    container_name: jabberish
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:watch
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27027:27027"